######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 7 22:38:00 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += test.h
SOURCES += main.cpp test.cpp
RC_FILE = test.rc
